config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'display_users', to: 'pages#index'

  get 'current_news', to: 'current_news#index'

  get 'display_chart', to: 'chart_data#index'





  
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :current_news, dependent: :destroy

end

app/models/chart_data.rb
class ChartData

  def self.get_current_news_group_by_published
    CurrentNews.group_by_week(:published).count
  end

  def self.get_trend_data(search_word, no_of_days)
    chart_date = [];
    time = Time.new
    #go to start date so time will be the start date
    time = time.prev_day(day = no_of_days - 1)
    (1..no_of_days).each do
      start_time = time.beginning_of_day()
      end_time = time.end_of_day()
      # prev two lines to get start time 2021-09-13 00:00:00 -----  2021-09-13 23:59:59
      #beginning_of_day() --> 2021-09-13 00:00:00 
      search_results = CurrentNews.where('title like ?', "%#{search_word}%")
      .or(CurrentNews.where('description like ?', "%#{search_word}%"))
      .where(published: start_time...end_time).count

      # add to the beginning of array then go to the next day
      chart_date.push([time.strftime("%F"), search_results])
      time = time.next_day(day = 1)
    end
    return chart_date
  end
  
end
  

app/models/current_news.rb
class CurrentNews < ApplicationRecord
  belongs_to :category
  #to be sure there is no duplicated current news
  validates :id_news,
  presence: true,
  uniqueness: true
  # even we have default value in config file for all paginations file
  # we can set a specific value for a specific module
  paginates_per 20
  scope :with_published_DESC, -> { order('published DESC') }
  
  
  def self.get_current_news_by_category(id)
    CurrentNews.where(category_id: id)
  end

  def self.get_current_news_in_date(published_date)
    start_time = published_date.beginning_of_day()
    end_time = published_date.end_of_day()
    search_results = CurrentNews.where(published: start_time...end_time)
  end

  def self.get_current_news_by_category_in_date(id, published_date)
    start_time = published_date.beginning_of_day()
    end_time = published_date.end_of_day()
    search_results = CurrentNews.where(published: start_time...end_time)
    .where(category_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :trackable, :confirmable
end

app/controllers/api_current_news_controller.rb
class ApiCurrentNewsController < ApplicationController
  def index
    @current_news = CurrentNews.find_each
    render json: @current_news, status: :ok
  end
  
  def show 
    @current_news = CurrentNews.where(category_id: params[:category_id])
    render json: @current_news, status: :ok
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.find_each
    render json: @categories, status: :ok
  end

end

app/controllers/chart_data_controller.rb
class ChartDataController < ApplicationController
  def index
    #chart for all categories
    @categories = Category.find_each

    # Full chart all current news group by published date
    @current_news_by_published = 
      ChartData.get_current_news_group_by_published()

    # Trend chart seacrh by user (search word and no of days)
    @show_trend_chart = false
    if trend_text().present?
      @trend_data = 
        ChartData.get_trend_data(trend_text(), no_of_days())
      @search_word = trend_text()#pass in to view
      @show_trend_chart = true
    end

  end

  private

    def trend_text
      params[:trend_text]
    end

    def no_of_days
      params[:days_no].to_i
    end

end

app/controllers/current_news_controller.rb
class CurrentNewsController < ApplicationController
  def index 
    @categories = Category.find_each
    @current_news = get_current_news()

    # to pass in for view stuff for the user to know which date and which category he/she select
    @selected_published = fill_in_published()
    @selected_category = fill_in_category_name()
  end

  private

    def category_id()
      params[:category]["id"].to_i
    end

    def published_date()
      Date.civil(params[:published][:"date(1i)"].to_i,
        params[:published][:"date(2i)"].to_i,
        params[:published][:"date(3i)"].to_i) 
    end

    def fill_in_category_name()
      if params[:select_category] == "1"
        Category.find(category_id()).category_name
      else
        "All categories"
      end
    end

    def fill_in_published()
      if params[:select_published_date] == "1"
        "in " + published_date().to_s
      else
        "in Entire time"
      end
    end

    def search_options()
      @option = "all options"
      if params[:select_category] == "1" && params[:select_published_date] == "1"
        @option = "both options"
      elsif params[:select_published_date] == "1"
          @option = "date option"
      elsif params[:select_category] == "1"
        @option = "category option"
      end
    end

    def search_current_news_methods()
      case @option
      when "both options" # Published & category : search by published & category
        CurrentNews.get_current_news_by_category_in_date(category_id(), published_date())
      when "date option" # Published : search by published
        CurrentNews.get_current_news_in_date(published_date())
      when "category option" # Category : search by category
        CurrentNews.get_current_news_by_category(category_id())
      else # All current news
        CurrentNews
      end
    end

    def get_current_news()
      search_options()
      search_current_news_methods().with_published_DESC.page params[:page]
    #.page params[:page] for kaminari pagination
    end
end

app/controllers/filter_category_controller.rb
class FilterCategoryController < ApplicationController
  def index
    category = Category.find(params[:category_id])
    category_filter = category.current_news.group_by_day(:published).count
    chart_data = category_filter.to_a
    render json: chart_data, status: :ok
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index 
    @users = User.find_each
  end
end

app/helpers/api_current_news_helper.rb
module ApiCurrentNewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/chart_data_helper.rb
module ChartDataHelper
end

app/helpers/current_news_helper.rb
module CurrentNewsHelper
end

app/helpers/filter_category_helper.rb
module FilterCategoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chart_data/index.html.erb
<%= link_to 'Back to Latest News', current_news_path, class: "btn btn-info m-4 d-block"%>

<%= form_with url: display_chart_path, class: "m-4 d-block border border-info p-3", method: :get do |form| %>
  <h1>TRENDING</h1>
  <%= form.label :trend_text, "Search for:" %>
  <%= form.text_field :trend_text, required: true, class: "m-4" %>
  <%= form.label :days_no, "number of prev days:" %>
  <%= form.text_field :days_no, required: true, class: "m-4" %>
  <%= form.submit "Search", class: "btn btn-success" %>
<% end %>

<hr/>
<div class="chart_section">
  <% if @show_trend_chart %>
  <h2>Trend "<%= @search_word %>"</h2>
  <%= column_chart @trend_data,
   colors: ["#b00", "#666", "#aa1", "#ff3"]%>
  <hr/>
  <% end %>
</div>

<div class="chart_section">
  <h2 class="mb-4">Current News group category by published date</h2>
  <%= line_chart @categories.map {|category|
  {name: category.category_name,
    data: category.current_news.group_by_day(:published).count}
  }%>
</div>

<hr/>
<div class="chart_section">
  <%= pie_chart @current_news_by_published,
  title: "Current News group published", download: true%>
</div>

<hr/>

app/views/current_news/index.html.erb
<%= link_to 'Go to chart', display_chart_path, class: "btn btn-info m-4 d-block"%>
<%= form_with url: current_news_path, class: "form-check m-4 border border-info p-5", method: :get do |form| %>
<%= form.label :published_date, "Current news in:" %>
<%= date_select('published', 'date', :published_date => [:month, :day, :year])%>
<%= form.check_box :select_published_date, class: "form-check-input"%></br>
<%= form.label :category, "Current news That its Category:" %>
<%= select(:category, "id", @categories.collect {|category| [ category.category_name, category.id ]}) %>
<%= form.check_box :select_category, class: "form-check-input" %>
<%= form.submit "Search", class: "btn btn-success d-block" %>
<% end %>
<%= paginate @current_news %>  


 <h1><%= @selected_category%> <%= @selected_published %></h1>
<table class="table mt-3">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Category</th>
    <th>Details</th>
    <th>Published</th>
  </tr> 

 <% for news in @current_news %>
  <tr>
    <td class="news_current_column_width"><span><%= news.title %></span></td>
    <td class="news_current_column_width"><%= news.author %></td>
    <td class="news_current_column_width"><%= news.category.category_name %></td> 
    <td class="news_current_column_width"><%= link_to 'more details', news.url %></td>
    <td class="news_current_column_width"><%= news.published %></td>
  </tr>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcom To our secure App | TREND</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Zen+Loop:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>
    
    <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
           <% if user_signed_in? && current_user.admin %>
             <span ><%= link_to "Dashboard", display_users_path, class: "btn btn-dark m-2"%></span>
            <% end %> 
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <span class="nav-link active">
                  <%= link_to "Home", root_path %>
                  </span>
                </li>
                 <li class="nav-item">
                  <span class="nav-link">
                    <%=  link_to "Current News", current_news_path %>
                  </span>
                </li>
              
                <% if user_signed_in? %>

                 <li class="nav-item">
                  <span class="nav-link">

                   Signin count: <%= current_user.sign_in_count %>
                  </span>
                </li>
                
                <li class="nav-item">
                  <span class="nav-link">
                  <%= link_to "Manage my account", edit_user_registration_path %>
                  </span>
                </li> 

                <li class="nav-item">
                  <span class="nav-link">
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </span>
                </li>
                <% else %>
                <li class="nav-item">
                  <span class="nav-link">
                    <%=  link_to "Log in", user_session_path %>
                  </span>
                </li>

                <li class="nav-item">
                  <span class="nav-link">
                    <%=  link_to "Sign up", new_user_registration_path %>
                  </span>
                </li>
                <% end %>
               
              </ul>
            </div>
          </div>
        </nav>
      
      </header>
      <div class="container mt-3 fs-3 p-2">
        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert">
            <%= flash.now[:notice]%>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-warning" role="alert">
            <%= flash.now[:alert] %>
          </div>
        <% end %>
      </div>
      <div class="container">
        <% if user_signed_in?%>
          <span>logged in as <span class="logged_email_color"><%= current_user.email%></span></span>
        <% end%>
        <%= yield %>
      </div>
    <script src="//cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center">Devise & API & Table & Chart & Test</h1>
<div class="container">
  <ul class="list-group">
    <li class="list-group-item">User can sign up</li>
    <li class="list-group-item">User can sign in</li>
    <li class="list-group-item">User can logout</li>
    <li class="list-group-item">User can change password</li>
    <li class="list-group-item">User can delete their own account</li>
    <li class="list-group-item">Account gets locked after 10 retries and user can unlock</li>
    <li class="list-group-item">User can confirm their account and is required to within 24 hours</li>
    <%
=begin%>
 <li class="list-group-item">User can see how many logins they have made: <%= current_user.sign_in_count%></li>  
<%
=end%>
    <li class="list-group-item">Admin can see index of users and all their attributes</li>
    <li class="list-group-item">decide what you want to build</li>
    <li class="list-group-item">select a publicly accessible data source (typically json api)</li>
    <li class="list-group-item">persist that data to your postgres database</li>
    <li class="list-group-item">create ERD and attach to this story</li>
    <li class="list-group-item">user can filter the charts and table</li>
    <li class="list-group-item">user can see data table</li>
    <li class="list-group-item">user can see chart of the data</li>
    <li class="list-group-item">only logged in users can see the table and charts</li>
    <li class="list-group-item">write specs for worker classes</li>
    <li class="list-group-item">write specs for the service classes</li>
  </ul>
</div>

app/views/pages/index.html.erb
<h1>Dashbord</h1>
<main>
  <h1 class= "text-center fs-3">Our Team</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Position</th>
        <th scope="col">Sign in count</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.email %></td>
        <td><%= user.admin ? "Admin" : "User" %></td>
        <%
=begin%>
 <td><%= user.sign_in_count %></td>  
<%
=end%>
      </tr>
      <% end %>
    </tbody>
  </table>
</main>